[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = [
  'npm ci --include=dev',
  'npx tsc',
  'echo "✅ TypeScript compilation completed"'
]

[start]
cmd = 'npm start'